# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351dbaff15477c1f8dd228d5bf7db1a74071c80f1d370c5f61a66a10255ea23e3fcc885927519b9ff9ba7053dd1e822d2702100d4fbd97100696836db306f150

test:
  secret_key_base: 9c9c2ddba4d287510765ec7f92344197c7774adc0281ac57d6f006a2e6d72d8e90b60644856609eaf2305cf71a7358763b9f5b4f0025c6de23ff447ae498e16c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
